### PR TITLE
Updated for KSP 1.2

### PR DESCRIPTION
**Pull request by ianperez**
Updated version to 2.9.5

### CODE REVIEW

**Comment by xytovl** [comment]
This will let the plugin compile for 1.2, but the algorithm does not work anymore. Fuel flow rules have been changed and staging will be wrong in some cases.

**Comment by ianperez** [comment]
I see.  I can work on the fuel flow changes if you like, but I would appreciate any direction you might be able to give.

**Comment by xytovl** [comment]
I have not looked at the new model so I can't really give advice on the changes required.
The method to look where to take fuel and apply consumption needs to be updated, but now it depends on the stage where the tanks are decoupled. The algorithm as initially designed can not work this way, so either a brand new algorithm should be designed or we would have to cheat and somehow set the fuel priority to what we have used during computation...

**Comment by ianperez** [comment]
Do you have an example craft that exhibits this issue?  I'm having trouble coming up with something that would not work with the current logic.  Mostly because when placing tanks in symmetry mode you can't give them different fuel flow priorities (when you change one they all change).

**Comment by ianperez** [comment]
I was able to make this craft by placing the tanks without symmetry and using the move tool to align them.  It uses asparagus style staging by enabling crossfeed on the decouplers and then adjusting the fuel flow priorities on the tanks.  In this case SmartStage does not create the proper stages.  Is this the case you were referring to, or is there something else as well?

[SmartStage Test.zip](https://github.com/xytovl/SmartStage/files/525280/SmartStage.Test.zip)

**Pull request merged**
